SELECT to_char(B.SALES_DATE,'YYYY') AS YEAR, to_number(to_char(B.SALES_DATE,'MM')) AS MONTH ,GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
GROUP BY to_char(B.SALES_DATE,'YYYY'), to_number(to_char(B.SALES_DATE,'MM')),GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;