SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A ,CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_ID = B.CAR_ID AND 
A.CAR_TYPE = '세단' AND 
to_char(B.START_DATE,'YYYY-MM') LIKE '2022-10'
ORDER BY A.CAR_ID DESC;